version: "3"
services:
  mod-docker:
    image: mod-docker:latest
    container_name: mod-docker
    environment:
      - MOD_USER=${MOD_USER}
    volumes:
      - /dev/shm:/dev/shm:rw
      - ./pedalboards:/mod/.pedalboards  
    devices:
      - /dev/snd
    build:
      context: ./mod-docker
    ulimits:
      memlock: 819200000
      rtprio: 99
    ports:
      - 8888:8888
