version: "3"
services:
  mod-docker:
    image: mod-docker:latest
    container_name: mod-docker
    environment:
      - USER_NAME=${USER_NAME}
      - GROUP_NAME=${GROUP_NAME}
      - USER_ID=${USER_ID}
      - GROUP_ID=${GROUP_ID}
    volumes:
      - /dev/shm:/dev/shm:rw
    devices:
      - /dev/snd
    build:
      context: ./mod-docker
    ulimits:
      memlock: 819200000
      rtprio: 99
    ports:
      - 8888:8888
